/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#00113a",
        "on-primary": "#ffffff",
        "primary-container": "#002366",
        "on-primary-container": "#758dd5",
        "primary-fixed": "#dbe1ff",
        "primary-fixed-dim": "#b3c5ff",
        "on-primary-fixed": "#00174a",
        "on-primary-fixed-variant": "#2a4386",
        secondary: "#775a19",
        "on-secondary": "#ffffff",
        "secondary-container": "#fed488",
        "on-secondary-container": "#785a1a",
        "secondary-fixed": "#ffdea5",
        "secondary-fixed-dim": "#e9c176",
        "on-secondary-fixed": "#261900",
        "on-secondary-fixed-variant": "#5d4201",
        surface: "#faf8ff",
        "surface-dim": "#dad9e0",
        "surface-bright": "#faf8ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f4f3f9",
        "surface-container": "#efedf3",
        "surface-container-high": "#e9e7ee",
        "surface-container-highest": "#e3e2e8",
        "surface-gray": "#F8F9FA",
        "on-surface": "#1a1b20",
        "on-surface-variant": "#444650",
        "inverse-surface": "#2f3035",
        "inverse-on-surface": "#f1f0f6",
        background: "#faf8ff",
        "on-background": "#1a1b20",
        outline: "#757682",
        "outline-variant": "#c5c6d2",
        "surface-tint": "#435b9f",
        "border-neutral": "#E0E0E0",
        "success-green": "#1B5E20",
        "error-red": "#B71C1C",
        "warning-amber": "#F57F17",
        "info-blue": "#01579B",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
      },
      fontFamily: {
        "display-lg": ["Hanken Grotesk", "sans-serif"],
        "headline-lg": ["Hanken Grotesk", "sans-serif"],
        "headline-md": ["Hanken Grotesk", "sans-serif"],
        "title-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-sm": ["JetBrains Mono", "monospace"],
        "table-header": ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "title-md": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "table-header": ["13px", { lineHeight: "18px", fontWeight: "700" }],
      },
      spacing: {
        base: "8px",
        "sidebar-width": "260px",
        "container-max": "1440px",
        gutter: "24px",
        "margin-mobile": "16px",
      },
      borderRadius: {
        sm: "0.125rem",
        DEFAULT: "0.25rem",
        md: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
      },
      maxWidth: {
        "container-max": "1440px",
      },
    },
  },
  plugins: [],
}
